### ISSUE TITLE
wrong right and space hotkeys (the string is incorrect)

### ISSUE THREAD

**Issue by bigplayer-ai** [flower-ab/EldenRing-MelinasFingers#21]
Hey,
I noticed in melinas fingers there is a hot key error
roll is considered move down and move down is considered roll
![image](https://github.com/a-burlakov/melinas-fingers/assets/119108387/030b0de3-3359-477b-b010-d267b4360a60)

**Comment by a-burlakov** [comment]
Hey! Thanks, you're totally right. Funny thing is that already corrected, but I have not released a new release with this fix and others yet. I think I'll release version 1.00 tomorrow with this fix and some more things. :)

**Comment by bigplayer-ai** [comment]
Can you make it run in background when playing elden ring? Also how can I check if EAC is on or off?
