### ISSUE TITLE
it stopped working at all after the last update 1.0.0

### ISSUE THREAD

**Issue by bigplayer-ai** [flower-ab/EldenRing-MelinasFingers#24]
it stopped working at all after the last update 1.0.0

**Comment by a-burlakov** [comment]
Hmm, it works fine for me. 

Does it run for you at all?
If it is, may be there're some interesting things in journal? 
![image](https://github.com/a-burlakov/melinas-fingers/assets/51537176/72622cec-bef7-435d-bcc3-f834b266b1ea)
