### ISSUE TITLE
mouse related macros are invalid

### ISSUE THREAD

**Issue by orinwindy** [flower-ab/EldenRing-MelinasFingers#25]
In version 1.0.0, mouse related macros are invalid，But the version published on the nexus website is normal

**Comment by a-burlakov** [comment]
Please give an example. It did not support mouse macro from the very beginning actually...

**Comment by orinwindy** [comment]
I described several actual situations I encountered, let's take switching equipment as an example. When I tried to double wield a right handed weapon, my macro should be set to "interactive button+left mouse button (i.e. attack button)". However, the latest version 1.0.0 and the version on the Nexus website did not successfully complete this action. When I bound the attack button to a keyboard button, the 1.0.0 version still cannot complete this action, But the version on the nexus website can.

**Comment by orinwindy** [comment]
This project is so cool, I want to Chineseize this interface, but only datesheets.py has been completed so far.I found some amulets missing
