### ISSUE TITLE
Problem with interface language localization

### ISSUE THREAD

**Issue by orinwindy** [flower-ab/EldenRing-MelinasFingers#26]
Hello author, I would like to do some translation work for this interface language, but when I localize the string language in mainWindow. py, the program functionality will become invalid. Can you provide me with some suggestions or methods to help me complete the work of interface language localization?

**Comment by a-burlakov** [comment]
Hello! 

Actually. `mainWindow.py` is created indirectly via Qt Designer so you don't need no change it. Try to use things I mentioned in [UI Development](https://github.com/a-burlakov/melinas-fingers#ui-development) part in README.md. It will help.
