### ISSUE TITLE
how to use semi manual mode?

### ISSUE THREAD

**Issue by orinwindy** [flower-ab/EldenRing-MelinasFingers#27]
Automatic mode will first clear the current equipment. How does semi manual mode work? I have looked at the source code but am not sure how semi manual mode works? In fact, as someone who has just downloaded this software, they don't know how to use semi manual mode. Can you please briefly explain how to use semi manual mode? Or how does the semi manual mode operate.

**Comment by a-burlakov** [comment]
There's little tip in UI about it:

![image](https://github.com/a-burlakov/melinas-fingers/assets/51537176/f06cf5b3-860d-4b25-ad5c-8b8c8bacfe18)

So, for example you have a **sword** in inventory cell №2 and a **hammer** in inventory cell №8. And **semi-manual** mode is on. 

- At start Melina's Fingers doesn't knot what's in your right hand. 
- Then you press **sword** macro. When it's done, MF remembers that you're holding an item from cell №2 it you're right hand. 
- Then you press **hammer** macro. MF counts a path in your inventory to go from №2 cell to №8 cell. And that's much faster, as you don't need to wait for your right hand to empty and inventory reopening. And then MF remembers that you're holding an item from cell №8. And so on.

But actually there can be problems if MF remembers an item incorrectly. For example there could be a frame loss, so MF picked an item from cell №7 (missed a little), but remembers that you're holding an item from №8. If it is, you need to clear MF memory with **Recovery key**, so everything would start over.
