### ISSUE TITLE
Chinese interface completed！

### ISSUE THREAD

**Issue by orinwindy** [flower-ab/EldenRing-MelinasFingers#28]
I have finished the Chinese interface of this artifact, I would like to ask if you mind if I make it public to let more people know how cool this tool is (such as Nexusmods), of course, I will indicate the source and author,  And attach the GitHub site to bring you more stars, or I'll send you the file for you to publish publicly.  These are all fine.  I personally prefer the latter.  What do you think?

**Comment by a-burlakov** [comment]
Nice work, congratulations! 

I don't mind if you'll make your work public. But I'll ask you to share it yourself as I actually don't have former passion to this project and right now I'm busy with other Python tasks.

But anyway if you'll have more questions, feel free to ask! Also I think I'll return to Melina's Fingers after DLC release (oh god please let there be better netcode already after all these years) to refresh items and spells IDs and may add some little features.

**Comment by orinwindy** [comment]
This is the address of the nexus network
https://www.nexusmods.com/eldenring/mods/3805/?tab=files

**Comment by a-burlakov** [comment]
Saw the screenshot. Your UI looks pretty and clean!

But check if your file can be downloaded from Nexus. It is marked as suspicious now. That was with original Melina's Fingers too. I fixed that by writing to Nexus support so they would check it manually and make it downloadable.

**Comment by orinwindy** [comment]
I found this report, but I don't know how to solve it. I heard that you have sent a message to n.com, thank you very much.

**Comment by a-burlakov** [comment]
Here is my message to Nexus support, may be will be useful for you.

```
I want to to publish my utility here:
{NexusMods link}

Unfortunately, some of VirusTotal checks think that my utility has viruses, but actually it has not. I made my utility with Python language, and used it's tools to convert it to .exe. And that's a usual problem that some antiviruses thinks that every .exe file that was made via Python is suspicious.

If it's possible, I ask you to review it manually and allow me to publish it.

Thank you!

```

**Comment by orinwindy** [comment]
I have never posted mods on Nexus website before, and I don't know who you are sending the information to. Can you provide me with your email address or shipping address? This Chinese version still reports a toxic state.

**Comment by a-burlakov** [comment]
I just wrote to `support@nexusmods.com`.
