### ISSUE TITLE
【Update Question】About New DLC

### ISSUE THREAD

**Issue by a361570441** [flower-ab/EldenRing-MelinasFingers#30]
New DLC is coming Do you intend to update the archive analysis of new DLC content, such as the byte address correspondence table of new bosses, the correspondence table of new equipment, etc. I am very interested in your project and look forward to your updates. Or would you like to share how to get the correspondence between the BOSS address and the equipment address?

**Comment by a-burlakov** [comment]
Hello! I actually didn't found these IDs by myself. I found it somewhere I don't even remember. And after DLC release (may be 4-6 weeks) I'll search for new IDs on the internet.

I remember that [The Grand Archives](https://github.com/The-Grand-Archives)'s discord have some useful information, you can search there.
Also [here](https://docs.google.com/spreadsheets/d/e/2PACX-1vTgf7Mf5GimOROn1xeK0vWA8Px0h-T44k2N7A5sD73IoLxoHnfsjifWYKi6d39G5HAVJUgWxyBSTC7G/pubhtml#) is some useful table.
