### ISSUE TITLE
Move Right & Dodge wrong positions in settings

### ISSUE THREAD

**Issue by God-damnit-all** [flower-ab/EldenRing-MelinasFingers#4]
Move Right and Dodge seem to have their positions swapped in settings.

**Comment by a-burlakov** [comment]
May I ask for details? Never met an error with that within my testing.

**Comment by God-damnit-all** [comment]
> May I ask for details? Never met an error with that within my testing.

![image](https://user-images.githubusercontent.com/53661808/205563682-9f537d48-4b2d-49e6-aa15-2a63a17e8bd8.png)

It's just a visual issue.

**Comment by a-burlakov** [comment]
Wow, thank you! I didn't even notice. :) 

Will fix it soon.
