### ISSUE TITLE
Special handling for Tab

### ISSUE THREAD

**Issue by God-damnit-all** [flower-ab/EldenRing-MelinasFingers#6]
Tab is a pretty convenient key to hit that you can't bind to an elden rings control, so I wanted to use it. However, alt+tabbing triggers the hotkey. Could Tab receive special handling so that it doesn't trigger when alt is held down?

**Comment by a-burlakov** [comment]
Unfortunately, I couldn't do this. I tried to several days to make Melina's Fingers to ignore OS hotkeys if Elden Ring is running, but I sincerely don't know how to do this. So sorry for that.

**Comment by God-damnit-all** [comment]
> Unfortunately, I couldn't do this. I tried to several days to make Melina's Fingers to ignore OS hotkeys if Elden Ring is running, but I sincerely don't know how to do this. So sorry for that.

Is it not possible to have hotkeys that specifically require modifier keys to _not_ be held down?

**Comment by God-damnit-all** [comment]
@flower-ab I do feel like you misunderstood the request. OS hotkeys is one thing, but having a Melina's Finger's macro not fire if Alt is held down is another.

In AutoHotkey, if you're familiar with that, it would be the difference between binding `Tab::` and `*Tab::`

**Comment by a-burlakov** [comment]
Hm, give me an example, may be I'm talking about another problem.

I meant that if you will set "Alt+Tab" or "Alt+F4" or "Alt+Tab" hotkey in Melina's Finger, then the unility will send virtual keypresses to OS while Elden Ring is running. And if "Alt+Tab" will be virtually pressed while Elden Ring is running, there's no way to make OS to make ignore this keypress. OS will switch current window anyway. I didn't managed to fix it.

**Comment by a-burlakov** [comment]
> @flower-ab I do feel like you misunderstood the request. OS hotkeys is one thing, but having a Melina's Finger's macro not fire if Alt is held down is another.
> 
> In AutoHotkey, if you're familiar with that, it would be the difference between binding `Tab::` and `*Tab::`

Yeah, I misunderstood. But anyway, give me an example, please, so I would put it to backlog.

**Comment by God-damnit-all** [comment]
> > @flower-ab I do feel like you misunderstood the request. OS hotkeys is one thing, but having a Melina's Finger's macro not fire if Alt is held down is another.
> > In AutoHotkey, if you're familiar with that, it would be the difference between binding `Tab::` and `*Tab::`
> 
> Yeah, I misunderstood. But anyway, give me an example, please, so I would put it to backlog.

![image](https://user-images.githubusercontent.com/53661808/205565756-aba3b5c3-3f76-45c2-a5a1-2cc2844aa2fa.png)

Basically, if my Alt key is held down, I want this to _not_ activate when Tab is pressed.

Currently, it activates when I alt+tab out of the window.

**Comment by a-burlakov** [comment]
Damn, I understand now. Thank you so much, put it to backlog.
